default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: oa_hero_development

test:
  <<: *default
  database: oa_hero_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

cable:
  production:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>

queue:
  production:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>

cache:
  production:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
